trigger:
- main

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build

  displayName: 'npm install test and  build'

- script: npm run test
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/*.trx'

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: test_results
    artifactName: 'test-results'